env: development
app_name: app
cache: memory
log:
  channel: ["file", "console"]
  log_level: trace
  human_readable: true
database:
  host: 132.232.152.120
  port: 3306
  username: test
  password: T2GG8xy8RnMXte3N
  db_name: test
redis:
  host: "127.0.0.1"    # Redis服务器地址
  port: 6379           # Redis端口号
  password: ""         # Redis密码（如果没有可以留空）
  db: 0                # 使用的Redis数据库编号，默认0